### ISSUE TITLE
Change 'Role' 'Team' and 'Client' font weight to bold 

### ISSUE THREAD

**Issue by DiwyaDeSilva** [samarara/diwya-portfolio#16]
# Bug report

**What is the current behavior?**
'Role', 'team' and 'Client' font weight is not bolded. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
'Role', 'team' and 'Client' font weight should be bolded. 

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by samarara** [comment]
This is back?

**Comment by DiwyaDeSilva** [comment]
Yes!
